apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: collections.kabanero.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: CreationTimestamp is a timestamp representing the server time when
      this object was created. It is not guaranteed to be set in happens-before order
      across separate operations.
    name: Age
    type: date
  - JSONPath: .status.status
    description: Collection status.
    name: Status
    type: string
  group: kabanero.io
  names:
    kind: Collection
    listKind: CollectionList
    plural: collections
    singular: collection
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Collection is the Schema for the collections API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CollectionSpec defines the desired composition of a Collection
          properties:
            desiredState:
              type: string
            name:
              type: string
            repositoryUrl:
              type: string
            skipCertVerification:
              type: boolean
            version:
              type: string
            versions:
              items:
                description: CollectionVersion defines the desired composition of
                  a specific collection version.
                properties:
                  desiredState:
                    type: string
                  repositoryUrl:
                    type: string
                  skipCertVerification:
                    type: boolean
                  version:
                    type: string
                type: object
              type: array
              x-kubernetes-list-type: set
          type: object
        status:
          description: CollectionStatus defines the observed state of a collection
          properties:
            activeLocation:
              type: string
            activePipelines:
              items:
                description: PipelineStatus defines the observed state of the assets
                  located within a single pipeline .tar.gz.
                properties:
                  activeAssets:
                    items:
                      description: RepositoryAssetStatus defines the observed state
                        of a single asset in a respository, in the collection.
                      properties:
                        assetDigest:
                          type: string
                        assetName:
                          type: string
                        group:
                          type: string
                        kind:
                          type: string
                        namespace:
                          type: string
                        status:
                          type: string
                        statusMessage:
                          type: string
                        version:
                          type: string
                      type: object
                    type: array
                    x-kubernetes-list-type: set
                  digest:
                    type: string
                  name:
                    type: string
                  url:
                    type: string
                required:
                - digest
                - name
                - url
                type: object
              type: array
              x-kubernetes-list-type: set
            activeVersion:
              type: string
            availableLocation:
              type: string
            availableVersion:
              type: string
            images:
              items:
                description: Image defines a container image used by a collection
                properties:
                  id:
                    type: string
                  image:
                    type: string
                type: object
              type: array
              x-kubernetes-list-type: set
            status:
              type: string
            statusMessage:
              type: string
            versions:
              items:
                description: CollectionVersionStatus defines the observed state of
                  a specific collection version.
                properties:
                  images:
                    items:
                      description: Image defines a container image used by a collection
                      properties:
                        id:
                          type: string
                        image:
                          type: string
                      type: object
                    type: array
                    x-kubernetes-list-type: set
                  location:
                    type: string
                  pipelines:
                    items:
                      description: PipelineStatus defines the observed state of the
                        assets located within a single pipeline .tar.gz.
                      properties:
                        activeAssets:
                          items:
                            description: RepositoryAssetStatus defines the observed
                              state of a single asset in a respository, in the collection.
                            properties:
                              assetDigest:
                                type: string
                              assetName:
                                type: string
                              group:
                                type: string
                              kind:
                                type: string
                              namespace:
                                type: string
                              status:
                                type: string
                              statusMessage:
                                type: string
                              version:
                                type: string
                            type: object
                          type: array
                          x-kubernetes-list-type: set
                        digest:
                          type: string
                        name:
                          type: string
                        url:
                          type: string
                      required:
                      - digest
                      - name
                      - url
                      type: object
                    type: array
                    x-kubernetes-list-type: set
                  status:
                    type: string
                  statusMessage:
                    type: string
                  version:
                    type: string
                type: object
              type: array
              x-kubernetes-list-type: set
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
