// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kabanero) DeepCopyInto(out *Kabanero) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kabanero.
func (in *Kabanero) DeepCopy() *Kabanero {
	if in == nil {
		return nil
	}
	out := new(Kabanero)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kabanero) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KabaneroList) DeepCopyInto(out *KabaneroList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kabanero, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KabaneroList.
func (in *KabaneroList) DeepCopy() *KabaneroList {
	if in == nil {
		return nil
	}
	out := new(KabaneroList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KabaneroList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KabaneroSpec) DeepCopyInto(out *KabaneroSpec) {
	*out = *in
	out.Tekton = in.Tekton
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KabaneroSpec.
func (in *KabaneroSpec) DeepCopy() *KabaneroSpec {
	if in == nil {
		return nil
	}
	out := new(KabaneroSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KabaneroStatus) DeepCopyInto(out *KabaneroStatus) {
	*out = *in
	out.Tekton = in.Tekton
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KabaneroStatus.
func (in *KabaneroStatus) DeepCopy() *KabaneroStatus {
	if in == nil {
		return nil
	}
	out := new(KabaneroStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TektonCustomizationSpec) DeepCopyInto(out *TektonCustomizationSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TektonCustomizationSpec.
func (in *TektonCustomizationSpec) DeepCopy() *TektonCustomizationSpec {
	if in == nil {
		return nil
	}
	out := new(TektonCustomizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TektonStatus) DeepCopyInto(out *TektonStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TektonStatus.
func (in *TektonStatus) DeepCopy() *TektonStatus {
	if in == nil {
		return nil
	}
	out := new(TektonStatus)
	in.DeepCopyInto(out)
	return out
}
