apiVersion: v1
kind: Namespace
metadata:
  name: openshift-pipelines-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-pipelines-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openshift-pipelines-operator
  template:
    metadata:
      labels:
        name: openshift-pipelines-operator
    spec:
      serviceAccountName: openshift-pipelines-operator
      containers:
      - name: openshift-pipelines-operator
        image: quay.io/openshift-pipeline/openshift-pipelines-operator:v0.5.0
        command:
        - openshift-pipelines-operator
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "openshift-pipelines-operator"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: openshift-pipelines-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - pods/log
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  - deployments/finalizers
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - build.knative.dev
  resources:
  - builds
  - buildtemplates
  - clusterbuildtemplates
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments/finalizers
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - get
  - create
  - update
  - delete
  - use
- apiGroups:
  - operator.tekton.dev
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - tekton.dev
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-pipelines-operator
subjects:
- kind: ServiceAccount
  name: openshift-pipelines-operator
  # NOTE: replace this with the namespace the operator is deployed in.
  namespace: openshift-pipelines-operator
roleRef:
  kind: ClusterRole
  name: openshift-pipelines-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-pipelines-operator
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: config.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: Config
    listKind: ConfigList
    plural: config
    singular: config
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            targetNamespace:
              description: namespace where OpenShift pipelines will be installed
              type: string
          required:
          - targetNamespace
          type: object
        status:
          properties:
            conditions:
              description: installation status sorted in reverse chronological order
              items:
                properties:
                  code:
                    description: Code indicates the status of installation of pipeline resources.
                    type: string
                  details:
                    description: Additional details about the Code
                    type: string
                  version:
                    description: The version of tekton pipelines
                    type: string
                required:
                - code
                - version
                type: object
              type: array
          type: object
  additionalPrinterColumns:
  - JSONPath: ".status.conditions[0].code"
    name: status
    type: string
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
